name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
    paths:
    - 'src/main.py'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/main.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows


